spring:
  data:
    mongodb:
      authentication-database: admin
      host: ${UNDERCONTROL_MONGO_HOST:192.168.50.230}
      port: ${UNDERCONTROL_MONGO_PORT:27017}
      database: ${UNDERCONTROL_MONGO_DATABASE:undercontrol}
      username: ${UNDERCONTROL_MONGO_USERNAME:mongoadmin}
      password: ${UNDERCONTROL_MONGO_PASSWORD:secret}

server:
  port: 8088

undercontrol:
  its-me: ${UNDERCONTROL_ITS_ME:c9113d5f-03dd-4407-94de-4b4f2462ca0a-its-me-lintao}
